# Generated by Django 5.0.4 on 2024-07-02 16:04

import main_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_videogame_release_year_alter_videogame_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogame',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[main_app.validators.validate_rating]),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
