# Generated by Django 5.0.4 on 2024-06-24 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_lecturerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerprofile',
            name='lecturer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.lecturer'),
        ),
    ]
