# Generated by Django 5.0.4 on 2024-06-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_laptop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='operating_system',
            new_name='operation_system',
        ),
    ]
