# Generated by Django 5.0.4 on 2024-06-28 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_menureview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('review_content', models.TextField()),
            ],
            options={
                'ordering': ['-rating'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='MenuReview',
        ),
    ]
