# Generated by Django 5.0.4 on 2024-06-28 13:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_meta_delete_menureview'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('review_content', models.TextField()),
                ('reviewer_name', models.CharField(max_length=100)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.menu')),
            ],
            options={
                'verbose_name': 'Menu Review',
                'verbose_name_plural': 'Menu Reviews',
                'ordering': ['-rating'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Meta',
        ),
        migrations.AddIndex(
            model_name='menureview',
            index=models.Index(fields=['menu'], name='main_app_menu_review_menu_id'),
        ),
        migrations.AlterUniqueTogether(
            name='menureview',
            unique_together={('reviewer_name', 'menu')},
        ),
    ]
