"""add chef table and relations

Revision ID: da5b138d3eb8
Revises: f373e64a6557
Create Date: 2024-07-04 17:11:40.848274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da5b138d3eb8'
down_revision: Union[str, None] = 'f373e64a6557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('recipes', sa.Column('chief_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'recipes', ['id'])
    op.create_foreign_key(None, 'recipes', 'chefs', ['chief_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_constraint(None, 'recipes', type_='unique')
    op.drop_column('recipes', 'chief_id')
    op.drop_table('chefs')
    # ### end Alembic commands ###
