# Generated by Django 5.0.4 on 2024-07-05 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='story_line',
            new_name='storyline',
        ),
    ]
